[package]
name = "asyncsync"
version = "0.1.0"
edition = "2021"

[features]
default = []
local = []

[dependencies]
parking_lot = "0.12.1"

[dev-dependencies]
tokio = { version = "1.19.2", features = ["rt", "rt-multi-thread", "macros", "test-util"] }
